// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: squad-cli.proto

package com.squad.protobuf.cli.packet;

public final class SquadCli {
  private SquadCli() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.squad.cli.packet.NodeEventType}
   */
  public enum NodeEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NODE_CREATED = 1;</code>
     */
    NODE_CREATED(0, 1),
    /**
     * <code>NODE_DATA_CHANGED = 2;</code>
     */
    NODE_DATA_CHANGED(1, 2),
    /**
     * <code>NODE_DELETED = 3;</code>
     */
    NODE_DELETED(2, 3),
    ;

    /**
     * <code>NODE_CREATED = 1;</code>
     */
    public static final int NODE_CREATED_VALUE = 1;
    /**
     * <code>NODE_DATA_CHANGED = 2;</code>
     */
    public static final int NODE_DATA_CHANGED_VALUE = 2;
    /**
     * <code>NODE_DELETED = 3;</code>
     */
    public static final int NODE_DELETED_VALUE = 3;


    public final int getNumber() { return value; }

    public static NodeEventType valueOf(int value) {
      switch (value) {
        case 1: return NODE_CREATED;
        case 2: return NODE_DATA_CHANGED;
        case 3: return NODE_DELETED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NodeEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<NodeEventType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NodeEventType>() {
            public NodeEventType findValueByNumber(int number) {
              return NodeEventType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.squad.protobuf.cli.packet.SquadCli.getDescriptor().getEnumTypes().get(0);
    }

    private static final NodeEventType[] VALUES = values();

    public static NodeEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private NodeEventType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.squad.cli.packet.NodeEventType)
  }

  public interface SquadCliPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.squad.cli.packet.SquadCliPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
     */
    com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command getCommand();

    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    boolean hasNodeEventPacket();
    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket getNodeEventPacket();
    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder getNodeEventPacketOrBuilder();
  }
  /**
   * Protobuf type {@code com.squad.cli.packet.SquadCliPacket}
   */
  public static final class SquadCliPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.squad.cli.packet.SquadCliPacket)
      SquadCliPacketOrBuilder {
    // Use SquadCliPacket.newBuilder() to construct.
    private SquadCliPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SquadCliPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SquadCliPacket defaultInstance;
    public static SquadCliPacket getDefaultInstance() {
      return defaultInstance;
    }

    public SquadCliPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SquadCliPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command value = com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 18: {
              com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder subBuilder = null;
              if (packetCase_ == 2) {
                subBuilder = ((com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_).toBuilder();
              }
              packet_ = input.readMessage(com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_);
                packet_ = subBuilder.buildPartial();
              }
              packetCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_SquadCliPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_SquadCliPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.class, com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<SquadCliPacket> PARSER =
        new com.google.protobuf.AbstractParser<SquadCliPacket>() {
      public SquadCliPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SquadCliPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SquadCliPacket> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.squad.cli.packet.SquadCliPacket.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STATUS = 1;</code>
       */
      STATUS(0, 1),
      /**
       * <code>LEADER = 2;</code>
       */
      LEADER(1, 2),
      /**
       * <code>SYNC = 3;</code>
       */
      SYNC(2, 3),
      /**
       * <code>START = 4;</code>
       */
      START(3, 4),
      /**
       * <code>SUSPEND = 5;</code>
       */
      SUSPEND(4, 5),
      /**
       * <code>STOP = 6;</code>
       */
      STOP(5, 6),
      /**
       * <code>NODES = 7;</code>
       */
      NODES(6, 7),
      /**
       * <code>NODE_EVENT = 8;</code>
       */
      NODE_EVENT(7, 8),
      ;

      /**
       * <code>STATUS = 1;</code>
       */
      public static final int STATUS_VALUE = 1;
      /**
       * <code>LEADER = 2;</code>
       */
      public static final int LEADER_VALUE = 2;
      /**
       * <code>SYNC = 3;</code>
       */
      public static final int SYNC_VALUE = 3;
      /**
       * <code>START = 4;</code>
       */
      public static final int START_VALUE = 4;
      /**
       * <code>SUSPEND = 5;</code>
       */
      public static final int SUSPEND_VALUE = 5;
      /**
       * <code>STOP = 6;</code>
       */
      public static final int STOP_VALUE = 6;
      /**
       * <code>NODES = 7;</code>
       */
      public static final int NODES_VALUE = 7;
      /**
       * <code>NODE_EVENT = 8;</code>
       */
      public static final int NODE_EVENT_VALUE = 8;


      public final int getNumber() { return value; }

      public static Command valueOf(int value) {
        switch (value) {
          case 1: return STATUS;
          case 2: return LEADER;
          case 3: return SYNC;
          case 4: return START;
          case 5: return SUSPEND;
          case 6: return STOP;
          case 7: return NODES;
          case 8: return NODE_EVENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Command(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.squad.cli.packet.SquadCliPacket.Command)
    }

    private int bitField0_;
    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public enum PacketCase
        implements com.google.protobuf.Internal.EnumLite {
      NODEEVENTPACKET(2),
      PACKET_NOT_SET(0);
      private int value = 0;
      private PacketCase(int value) {
        this.value = value;
      }
      public static PacketCase valueOf(int value) {
        switch (value) {
          case 2: return NODEEVENTPACKET;
          case 0: return PACKET_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PacketCase
    getPacketCase() {
      return PacketCase.valueOf(
          packetCase_);
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command command_;
    /**
     * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
     */
    public com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command getCommand() {
      return command_;
    }

    public static final int NODEEVENTPACKET_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    public boolean hasNodeEventPacket() {
      return packetCase_ == 2;
    }
    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket getNodeEventPacket() {
      if (packetCase_ == 2) {
         return (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_;
      }
      return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
    }
    /**
     * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
     */
    public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder getNodeEventPacketOrBuilder() {
      if (packetCase_ == 2) {
         return (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_;
      }
      return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
    }

    private void initFields() {
      command_ = com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command.STATUS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasNodeEventPacket()) {
        if (!getNodeEventPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      if (packetCase_ == 2) {
        output.writeMessage(2, (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      if (packetCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.squad.cli.packet.SquadCliPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.squad.cli.packet.SquadCliPacket)
        com.squad.protobuf.cli.packet.SquadCli.SquadCliPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_SquadCliPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_SquadCliPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.class, com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Builder.class);
      }

      // Construct using com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command.STATUS;
        bitField0_ = (bitField0_ & ~0x00000001);
        packetCase_ = 0;
        packet_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_SquadCliPacket_descriptor;
      }

      public com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket getDefaultInstanceForType() {
        return com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.getDefaultInstance();
      }

      public com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket build() {
        com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket buildPartial() {
        com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket result = new com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (packetCase_ == 2) {
          if (nodeEventPacketBuilder_ == null) {
            result.packet_ = packet_;
          } else {
            result.packet_ = nodeEventPacketBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.packetCase_ = packetCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket) {
          return mergeFrom((com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket other) {
        if (other == com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        switch (other.getPacketCase()) {
          case NODEEVENTPACKET: {
            mergeNodeEventPacket(other.getNodeEventPacket());
            break;
          }
          case PACKET_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (hasNodeEventPacket()) {
          if (!getNodeEventPacket().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packetCase_ = 0;
      private java.lang.Object packet_;
      public PacketCase
          getPacketCase() {
        return PacketCase.valueOf(
            packetCase_);
      }

      public Builder clearPacket() {
        packetCase_ = 0;
        packet_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command command_ = com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command.STATUS;
      /**
       * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
       */
      public com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command getCommand() {
        return command_;
      }
      /**
       * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
       */
      public Builder setCommand(com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.squad.cli.packet.SquadCliPacket.Command command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.squad.protobuf.cli.packet.SquadCli.SquadCliPacket.Command.STATUS;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder> nodeEventPacketBuilder_;
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public boolean hasNodeEventPacket() {
        return packetCase_ == 2;
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket getNodeEventPacket() {
        if (nodeEventPacketBuilder_ == null) {
          if (packetCase_ == 2) {
            return (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_;
          }
          return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
        } else {
          if (packetCase_ == 2) {
            return nodeEventPacketBuilder_.getMessage();
          }
          return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public Builder setNodeEventPacket(com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket value) {
        if (nodeEventPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packet_ = value;
          onChanged();
        } else {
          nodeEventPacketBuilder_.setMessage(value);
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public Builder setNodeEventPacket(
          com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder builderForValue) {
        if (nodeEventPacketBuilder_ == null) {
          packet_ = builderForValue.build();
          onChanged();
        } else {
          nodeEventPacketBuilder_.setMessage(builderForValue.build());
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public Builder mergeNodeEventPacket(com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket value) {
        if (nodeEventPacketBuilder_ == null) {
          if (packetCase_ == 2 &&
              packet_ != com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance()) {
            packet_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.newBuilder((com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_)
                .mergeFrom(value).buildPartial();
          } else {
            packet_ = value;
          }
          onChanged();
        } else {
          if (packetCase_ == 2) {
            nodeEventPacketBuilder_.mergeFrom(value);
          }
          nodeEventPacketBuilder_.setMessage(value);
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public Builder clearNodeEventPacket() {
        if (nodeEventPacketBuilder_ == null) {
          if (packetCase_ == 2) {
            packetCase_ = 0;
            packet_ = null;
            onChanged();
          }
        } else {
          if (packetCase_ == 2) {
            packetCase_ = 0;
            packet_ = null;
          }
          nodeEventPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder getNodeEventPacketBuilder() {
        return getNodeEventPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder getNodeEventPacketOrBuilder() {
        if ((packetCase_ == 2) && (nodeEventPacketBuilder_ != null)) {
          return nodeEventPacketBuilder_.getMessageOrBuilder();
        } else {
          if (packetCase_ == 2) {
            return (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_;
          }
          return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.squad.cli.packet.NodeEventPacket nodeEventPacket = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder> 
          getNodeEventPacketFieldBuilder() {
        if (nodeEventPacketBuilder_ == null) {
          if (!(packetCase_ == 2)) {
            packet_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
          }
          nodeEventPacketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder>(
                  (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) packet_,
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        packetCase_ = 2;
        return nodeEventPacketBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.squad.cli.packet.SquadCliPacket)
    }

    static {
      defaultInstance = new SquadCliPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.squad.cli.packet.SquadCliPacket)
  }

  public interface NodeEventPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.squad.cli.packet.NodeEventPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
     */
    boolean hasNodeEventType();
    /**
     * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
     */
    com.squad.protobuf.cli.packet.SquadCli.NodeEventType getNodeEventType();

    /**
     * <code>required string node = 2;</code>
     */
    boolean hasNode();
    /**
     * <code>required string node = 2;</code>
     */
    java.lang.String getNode();
    /**
     * <code>required string node = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeBytes();

    /**
     * <code>required bytes value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code com.squad.cli.packet.NodeEventPacket}
   */
  public static final class NodeEventPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.squad.cli.packet.NodeEventPacket)
      NodeEventPacketOrBuilder {
    // Use NodeEventPacket.newBuilder() to construct.
    private NodeEventPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NodeEventPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NodeEventPacket defaultInstance;
    public static NodeEventPacket getDefaultInstance() {
      return defaultInstance;
    }

    public NodeEventPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NodeEventPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.squad.protobuf.cli.packet.SquadCli.NodeEventType value = com.squad.protobuf.cli.packet.SquadCli.NodeEventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                nodeEventType_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              node_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_NodeEventPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_NodeEventPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.class, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<NodeEventPacket> PARSER =
        new com.google.protobuf.AbstractParser<NodeEventPacket>() {
      public NodeEventPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeEventPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NodeEventPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NODEEVENTTYPE_FIELD_NUMBER = 1;
    private com.squad.protobuf.cli.packet.SquadCli.NodeEventType nodeEventType_;
    /**
     * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
     */
    public boolean hasNodeEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
     */
    public com.squad.protobuf.cli.packet.SquadCli.NodeEventType getNodeEventType() {
      return nodeEventType_;
    }

    public static final int NODE_FIELD_NUMBER = 2;
    private java.lang.Object node_;
    /**
     * <code>required string node = 2;</code>
     */
    public boolean hasNode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string node = 2;</code>
     */
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          node_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string node = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      nodeEventType_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventType.NODE_CREATED;
      node_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNodeEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, nodeEventType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, nodeEventType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.squad.cli.packet.NodeEventPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.squad.cli.packet.NodeEventPacket)
        com.squad.protobuf.cli.packet.SquadCli.NodeEventPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_NodeEventPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_NodeEventPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.class, com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.Builder.class);
      }

      // Construct using com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeEventType_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventType.NODE_CREATED;
        bitField0_ = (bitField0_ & ~0x00000001);
        node_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.squad.protobuf.cli.packet.SquadCli.internal_static_com_squad_cli_packet_NodeEventPacket_descriptor;
      }

      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket getDefaultInstanceForType() {
        return com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance();
      }

      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket build() {
        com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket buildPartial() {
        com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket result = new com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeEventType_ = nodeEventType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.node_ = node_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) {
          return mergeFrom((com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket other) {
        if (other == com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket.getDefaultInstance()) return this;
        if (other.hasNodeEventType()) {
          setNodeEventType(other.getNodeEventType());
        }
        if (other.hasNode()) {
          bitField0_ |= 0x00000002;
          node_ = other.node_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNodeEventType()) {
          
          return false;
        }
        if (!hasNode()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.squad.protobuf.cli.packet.SquadCli.NodeEventPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.squad.protobuf.cli.packet.SquadCli.NodeEventType nodeEventType_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventType.NODE_CREATED;
      /**
       * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
       */
      public boolean hasNodeEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
       */
      public com.squad.protobuf.cli.packet.SquadCli.NodeEventType getNodeEventType() {
        return nodeEventType_;
      }
      /**
       * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
       */
      public Builder setNodeEventType(com.squad.protobuf.cli.packet.SquadCli.NodeEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        nodeEventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.squad.cli.packet.NodeEventType nodeEventType = 1;</code>
       */
      public Builder clearNodeEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeEventType_ = com.squad.protobuf.cli.packet.SquadCli.NodeEventType.NODE_CREATED;
        onChanged();
        return this;
      }

      private java.lang.Object node_ = "";
      /**
       * <code>required string node = 2;</code>
       */
      public boolean hasNode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string node = 2;</code>
       */
      public java.lang.String getNode() {
        java.lang.Object ref = node_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            node_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string node = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeBytes() {
        java.lang.Object ref = node_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string node = 2;</code>
       */
      public Builder setNode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string node = 2;</code>
       */
      public Builder clearNode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        node_ = getDefaultInstance().getNode();
        onChanged();
        return this;
      }
      /**
       * <code>required string node = 2;</code>
       */
      public Builder setNodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        node_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.squad.cli.packet.NodeEventPacket)
    }

    static {
      defaultInstance = new NodeEventPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.squad.cli.packet.NodeEventPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_squad_cli_packet_SquadCliPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_squad_cli_packet_SquadCliPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_squad_cli_packet_NodeEventPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_squad_cli_packet_NodeEventPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017squad-cli.proto\022\024com.squad.cli.packet\"" +
      "\205\002\n\016SquadCliPacket\022=\n\007command\030\001 \002(\0162,.co" +
      "m.squad.cli.packet.SquadCliPacket.Comman" +
      "d\022@\n\017nodeEventPacket\030\002 \001(\0132%.com.squad.c" +
      "li.packet.NodeEventPacketH\000\"h\n\007Command\022\n" +
      "\n\006STATUS\020\001\022\n\n\006LEADER\020\002\022\010\n\004SYNC\020\003\022\t\n\005STAR" +
      "T\020\004\022\013\n\007SUSPEND\020\005\022\010\n\004STOP\020\006\022\t\n\005NODES\020\007\022\016\n" +
      "\nNODE_EVENT\020\010B\010\n\006packet\"j\n\017NodeEventPack" +
      "et\022:\n\rnodeEventType\030\001 \002(\0162#.com.squad.cl" +
      "i.packet.NodeEventType\022\014\n\004node\030\002 \002(\t\022\r\n\005",
      "value\030\003 \002(\014*J\n\rNodeEventType\022\020\n\014NODE_CRE" +
      "ATED\020\001\022\025\n\021NODE_DATA_CHANGED\020\002\022\020\n\014NODE_DE" +
      "LETED\020\003B\037\n\035com.squad.protobuf.cli.packet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_squad_cli_packet_SquadCliPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_squad_cli_packet_SquadCliPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_squad_cli_packet_SquadCliPacket_descriptor,
        new java.lang.String[] { "Command", "NodeEventPacket", "Packet", });
    internal_static_com_squad_cli_packet_NodeEventPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_squad_cli_packet_NodeEventPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_squad_cli_packet_NodeEventPacket_descriptor,
        new java.lang.String[] { "NodeEventType", "Node", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
